version: '3.8'

services:
  datascienceproject:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MLFLOW_TRACKING_URI=https://dagshub.com/jagadeshchilla/datascienceProject.mlflow
      - MLFLOW_TRACKING_USERNAME=jagadeshchilla
      - MLFLOW_TRACKING_PASSWORD=${DAGSHUB_TOKEN}
      - FLASK_ENV=development
    volumes:
      # Mount source code for development (optional)
      - ./src:/app/src:ro
      - ./templates:/app/templates:ro
      # Mount artifacts for persistence
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
    networks:
      - ml-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ml-network:
    driver: bridge 